image: python:3.6-slim

stages:
  - install
  - test

setup:
  stage: install
  script:
    - pip3 install .
  tags:
    - light

all_tests:
  stage: test
  script:
    - python3 -m unittest discover
  tags:
    - light
  allow_failure: true # not finished writing these yet
