image: python:3.6-slim

stages:
  - setup
  - test

# -----------------------------------------------------------------------------
setup:py:
  stage: setup
  tags:
    - light
  script:
    - python3 setup.py test
    - python3 setup.py install

setup:pip:
  stage: setup
  tags:
    - light
  script:
    - pip3 install .

setup:venv:
  # NOTE This step is required for the next stages to have all dependencies:
  stage: setup
  tags:
    - light
  before_script:
    - pip3 install virtualenv       # not included in 3.6-slim
  script:
    - python3 -m virtualenv env     # creates it in the current directory
    - source ./env/bin/activate     # enter virtual environment
    - pip3 install .[test_deps]     # installation including test dependencies

test:all:
  stage: test
  dependencies:
    - setup:venv
  tags:
    - light
  script:
    - source ./env/bin/activate     # is passed over from last stage
    - python3 -m pytest --cov=paramspace tests/
  coverage: '/\d+\.\d+%$/'          # also set in GitLab CI/CD settings
