image: python:3.6-slim

stages:
  - install
  - test

setup:
  stage: install
  script:
    - pip3 install .
  tags:
    - light

all_tests:
  stage: test # TODO distinguish modules
  allow_failure: true # not finished writing these yet
  tags:
    - light
  script:
    - python3 -m unittest discover
  after_script:
    - pip3 install pytest-cov
    - py.test --cov=paramspace tests/ # TODO suppress testing here
  coverage: '\d+\%\s*$'
