image: python:3.6-slim

stages:
  - install
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/.pip-cache"
  key: "$CI_PROJECT_ID"

py_setup:
  stage: install
  tags:
    - light
  script:
    - python3 setup.py test
    - python3 setup.py install

pip_install:
  stage: install
  tags:
    - light
  script:
    - pip3 install .[test_deps] # full installation

paramspace:
  stage: test
  tags:
    - light
  script:
    - py.test --cov=paramspace tests/
  coverage: '/\d+\.\d+%$/' # also set in GitLab CI/CD settings
