# CI/CD based on tox and pytest
image: python

stages:
  - test

before_script:
  - pip install .[test_deps]

# -----------------------------------------------------------------------------

test:py35:
  image: python:3.5
  stage: test
  script:
    - tox -e py35

test:py36:
  image: python:3.6
  stage: test
  script:
    - tox -e py36

test:py37:
  image: python:3.7
  stage: test
  script:
    - tox -e py37
