# CI/CD based on tox and pytest
image: python

stages:
  - test
  - test_minimal_deps

before_script:
  - pip install tox

# -----------------------------------------------------------------------------

test:py36:
  image: python:3.6
  stage: test
  script:
    - tox -e py36

test:py37:
  image: python:3.7
  stage: test
  script:
    - tox -e py37

test:py38:
  image: python:3.8
  stage: test
  script:
    - tox -e py38

# -----------------------------------------------------------------------------
# Test again using the lower bound of the python dependencies

test_minimal_deps:py36: &minimal
  image: python:3.6
  stage: test_minimal_deps
  allow_failure: true
  needs:
    - test:py36
  script:
    - tox -e py36-minimal_deps

test_minimal_deps:py37:
  <<: *minimal
  image: python:3.7
  needs:
    - test:py37
  script:
    - tox -e py37-minimal_deps

test_minimal_deps:py38:
  <<: *minimal
  image: python:3.8
  needs:
    - test:py38
  script:
    - tox -e py38-minimal_deps
