# pre-commit configuration
---
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/timothycrosley/isort
    rev: master
    hooks:
      - id: isort
        additional_dependencies: [toml]
        verbose: true
        files: \.py$
        args: [--project=paramspace]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: end-of-file-fixer

      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      - id: check-yaml
        # args: [--unsafe]

      - id: forbid-new-submodules

  # Run this every now and again
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.0
    hooks:
    - id: pyupgrade
      args:
        - --py36-plus
      stages: [manual]
      verbose: true
