# pre-commit configuration
---
repos:
  # Manually run this every now and again .....................................
  # Command:  pre-commit run --all-files --hook-stage manual

  # Run if desiring to make use of newer language features
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
      name: upgrade python syntax
      args:
        - --py3-plus
        - --py36-plus
      stages: [manual]

  # Run when having added new package dependencies
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        name: seed isort config
        stages: [manual]

  # Default pre-commit hooks ..................................................
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: sort imports
        additional_dependencies: [toml]
        files: \.py$
        args: [--project=paramspace]

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        name: black code formatting

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: rst-backticks
        name: check RST backticks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        name: check YAML

      - id: end-of-file-fixer
        name: fix end of files

      - id: trailing-whitespace
        name: fix trailing whitespace
        args: [--markdown-linebreak-ext=md]
